# https://numtide.github.io/devshell

[devshell]
packages = [
  "cargo-tauri",
  "rustup",
  "rust-analyzer",

  "nodePackages_latest.typescript",
  "nodePackages_latest.typescript-language-server",
  "nodePackages_latest.vls"
]
